
#############################################
##                                         ##
##           Defaut setup                  ##
##                                         ##
#############################################
default_config:
bluetooth:
cloud:
api:
wake_on_lan:
discovery:
stream:
ffmpeg:

# Customize
homeassistant:
  customize: !include customize.yaml
  allowlist_external_dirs:
    - /tmp
    - /config/www
    - /media
#   media_dirs:
#     local: /media
    
# Themes
frontend:
#  javascript_version: latest
  themes: !include_dir_merge_named themes/
  extra_module_url:
    - /local/card-mod.js

    
    
#############################################
##                                         ##
##           Text to speech                ##
##                                         ##
#############################################  
tts:
  - platform: google_translate
    language: 'fr'
        
#############################################
##                                         ##
##              Scinder                    ##
##                                         ##
#############################################  
# Recorder
recorder: !include recorder.yaml

# Group
group: !include groups.yaml

# Automation
automation: !include automations.yaml

# Script
script: !include scripts.yaml

# Scene
scene: !include scenes.yaml

# Input Text
input_text: !include input_text.yaml

# Input Select
input_select: !include input_select.yaml

# ZHA
zha: !include zha.yaml 

# Light group groupe de lumières
light: !include light.yaml 

# shell_command
shell_command: !include shell_command.yaml

# aarlo sonnette
aarlo: !include aarlo.yaml

# Sonoff
sonoff: !include sonoff.yaml  
  
# homekit
homekit: !include homekit.yaml

# Calendrier iOS 
calendar: !include calendar.yaml

# Yeelight 
yeelight: !include yeelight.yaml        

# iOS actions Apple Watch 
ios: !include ios.yaml

# Home Connect (lave vaisselle) 
home_connect: !include home_connect.yaml

# Camera (aarlo, generic, aspis...) 
camera: !include camera.yaml

# webostv (TV salon) 
webostv: !include webostv.yaml

# binary_sensor 
binary_sensor: !include binary_sensor.yaml

# Template v2 
template: !include template.yaml  

# Device Tracker 
device_tracker: !include device_tracker.yaml

# Alarme 
alarm_control_panel: !include alarm_control_panel.yaml

# Doods
image_processing: !include doods.yaml

# Switch 
switch: !include switch.yaml

# utility_meter 
utility_meter: !include utility_meter.yaml

# command_line
command_line: !include command_line.yaml

# Sensor et Template v1
sensor: !include sensor.yaml

 
       

     
